import {
  IconBrandGithub,
  IconBrandInstagram,
  IconBrandLeetcode,
  IconBrandLinkedin,
  IconBrandTwitter,
  IconBrandYoutube,
} from "@tabler/icons-react";
const Info = {
  name: "Nikhil Singh",
  stack: [
    "Freelancer",
    "Software Engineer",
    "Full Stack Developer",
    "Frontend Developer",
    "Open Source Contributor",
  ],
  bio: "I'm a GET THINGS DONE Full Stack Developer with 2 years of experience in React, Next.js, Node.js, and Python. Skilled in building scalable web applications, optimizing performance, and implementing secure systems. Experienced in delivering impactful projects in fast-paced environments.",
  resume_name: "nikhil_resume_gmail.pdf",
};

const ProjectInfo = [
  {
    title: "Lawcrats - Legal AI",
    desc: [
      " Built and optimized a legal website interface with AI/ML features (chatbots, casesummarizers), boosting interaction speed by 30% and user retention by 20%.",
      "Collaborated with backend and AI/ML teams, improving automated assistance accuracy by25% and reducing query response times by 40%.",
    ],
    image: "lawcratsweb.png",
    live: true,
    technologies: [
      "ReactJs",
      "NodeJs",
      "Postgres SQL",
      "Typescript",
      "Tailwind",
      "Redux Toolkit",
      "ShadCN",
      "Type ORM",
      "Docker",
      "Digital Ocean",
    ],
    link: "https://www.lawcrats.com/",
    github: "",
  },
  {
    title: "Chatbot - All in One AI Generator",
    desc: [
      "Developed a fully responsive web application with Tailwind CSS, featuring advanced animations, React Server Components, Clerk-based authentication, and AI-powered tools for image, video, and conversation generation.",
      "Handled data operations with custom POST, DELETE, and GET routes in Next.js API handlers, fetched data directly in server components, and managed database relations seamlessly.",
      "Optimized performance using caching and memoization, ensuring fast page loads and smooth user experiences.",
      "Integrated Stripe for subscription management, including a free tier with API limiting.",
    ],
    image: "gemini.png",
    live: true,
    technologies: [
      "ReactJs",
      "Tailwind CSS",
      "React Server Components",
      "Stripe API",
      "React Hook Forms",
      "OpenAI API",
      "Replicate AI",
    ],
    link: "https://gemini-clone-ochre-three.vercel.app/",
    github: "https://github.com/nikhil8615/Gemini-clone",
  },
  {
    title: "Article Summarizer AI App",
    desc: [
      "A responsive, beautiful UI/UX with a nice touch of glass morphism using Tailwind CSS",
      "Utilizes advanced RTK query API requests that fire on condition",
      "Saves history using the local storage",
      "Handles form events and catch errors",
      "Implements copy to clipboard",
    ],
    image: "travel_blog.png",
    live: true,
    technologies: [
      "React.js",
      "RTK query",
      "Tailwind CSS",
      "Local Storage",
      "Copy to Clipboard",
    ],
    link: "https://github.com/nikhil8615/Tour-travel-website",
    github: "https://github.com/nikhil8615/Tour-travel-website",
  },
  {
    title: "Food Search App",
    desc: [
      "Food Search App is a food search and recipe provider application built with Vue.js, Tailwind CSS, and Axios. It leverages the themealdb API to deliver search results with debouncing and URL-based state management for seamless user experience.",
    ],
    image: "restraunt.png",
    live: true,
    technologies: [
      "React.js",
      "Tailwind CSS",
      "URL-based state management",
      "Axios",
    ],
    link: "https://restraunt-pink.vercel.app/",
    github: "https://github.com/nikhil8615/Restraunt",
  },
  {
    title: "Hardhat Fund Me Dapp",
    desc: [
      "Hardhat Fund Me Dapp is a decentralized application(Dapp) built with Hardhat, and Ethers.js. It provides a decentralized platform for users to fund projects using the Metamask wallet.",
    ],
    image: "hardhat.png",
    live: false,
    technologies: [
      "ethers.js",
      "Ganache",
      "Hardhat",
      "Metamask Wallet",
      "Remix IDE",
    ],
    link: "https://github.com/ChiragG2101/hardhat-fund-me/blob/main/README.md",
    github: "https://github.com/ChiragG2101/hardhat-fund-me",
  },
  {
    title: "Modern dashboard",
    desc: [
      "ZuAI is a modern, fully responsive dashboard built using Next.js, TailwindCSS, ShadCN and NextAuth for authentication and authorization. It provides a seamless user experience, with intuitive navigation and easy-to-use features.",
    ],
    image: "zu-ai.png",
    live: true,
    technologies: ["Next.js", "NextAuth", "ShadCN", "Tailwind CSS"],
    link: "https://zu-ai.vercel.app/",
    github: "https://github.com/ChiragG2101/zuAi",
  },
];

const SkillInfo = [
  {
    title: "Frontend",
    skills: [
      "HTML",
      "CSS",
      "SASS",
      "JavaScript",
      "React JS",
      "Next JS",
      "Tailwind CSS",
      "Vue",
      "Redux",
      "Recharts",
      "Material UI",
      "Jest",
      "Babel",
      //"Webpack",
      //"Three JS",
      // "Angular",
      // "Bootstrap",
    ],
  },
  {
    title: "Backend",
    skills: [
      // "Springboot",
      "Node JS",
      "Express JS",
      "Fast API",
      "MongoDB",
      "PostgresSQL",
      "Chroma DB",
      "Firebase",
    ],
  },
  {
    title: "Languages",
    skills: ["C", "C++", "JavaScript", "TypeScript", "Python"],
  },
  {
    title: "Tools",
    skills: [
      "Git",
      "Github",
      "VS Code",
      "Figma",
      "Docker",
      "Postman",
      //"MongoDB Compass",
      // "Spring Tool Suite",
    ],
  },
];
const socialLinks = [
  { link: "https://github.com/nikhil8615", icon: IconBrandGithub },
  {
    link: "https://www.linkedin.com/in/nikhil-singh-a83776256",
    icon: IconBrandLinkedin,
  },
  {
    link: "https://www.instagram.com/nikhil_singh_8615/?__pwa=1",
    icon: IconBrandInstagram,
  },

  //   {
  //     link: "https://www.youtube.com/channel/UC1ki6jaFvFiH_E79b9FYptw",
  //     icon: IconBrandYoutube,
  //   },
  { link: "https://leetcode.com/u/nikhil_8615/", icon: IconBrandLeetcode },
];

const ExperienceInfo = [
  {
    role: "Software Developer Intern",
    company: "Lawcrats",
    image: "lawcrats.png",
    date: "July 2024 - Present",
    desc: [
      "Designed and implemented an AI-powered chatbot integrated with MongoDB, providing users with seamless, real-time assistance for legal queries across various domains of law.",
      "Developed a sophisticated summarization tool to analyze and process PowerPoint presentations, extracting key legal insights and delivering concise, actionable summaries tailored to the needs of legal professionals.",
      "Built a feature-rich case search engine that enables users to efficiently retrieve comprehensive and precise information about specific legal cases, significantly enhancing research productivity and decision-making.",
    ],
    skills: [
      "React JS",
      "Typescript",
      "Tailwind CSS",
      "Redux Toolkit",
      "Python",
      "Fast API",
      "MongoDB",
      "LLMs",
      "AI/ML",
    ],
  },

  {
    role: "Frontend Developer Intern",
    company: "WebCrafts",
    image: "webcrafts.png",
    date: "May 2024 - July 2024",
    desc: [
      "Developed a dynamic, user-friendly & mobile-responsive Finlight community webpage, which garnered over 2000+ members on launch day",
      "Designed and implemented the coupon system in the admin panel, connecting it with frontend using REST APIs",
    ],
    skills: [
      "React.js",
      "Next.js",
      "Redux",
      "Tailwind CSS",
      "Material UI(MUI)",
      "Node.js",
    ],
  },
];
const Slugs = [
  "typescript",
  "spring",
  "javascript",
  "dart",
  "java",
  "react",
  "angular",
  "flutter",
  "android",
  "html5",
  "css3",
  "springboot",
  "mongodb",
  "selenium",
  "nodedotjs",
  "express",
  "nextdotjs",
  "prisma",
  "mysql",
  "amazonaws",
  "postgresql",
  "firebase",
  "nginx",
  "vercel",
  "testinglibrary",
  "jest",
  "cypress",
  "docker",
  "git",
  "jira",
  "github",
  "gitlab",
  "visualstudiocode",
  "androidstudio",
  "sonarqube",
  "figma",
];
export { Info, ProjectInfo, socialLinks, SkillInfo, ExperienceInfo, Slugs };
